# Generated by Django 6.0 on 2026-01-01 21:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_id', models.UUIDField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['room_id', 'from_date', 'to_date'], name='api_reserva_room_id_e5868e_idx'), models.Index(fields=['delete_at'], name='api_reserva_delete__199743_idx')],
            },
        ),
    ]
